=== Wireless-Innovation-Forum/Spectrum-Access-System/schema/PalRecord.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "PAL record parameters from WINNF-TS-0245 Version V1.0.0",
  "type": "object",
  "required": [
    "palId",
    "userId",
    "registrationInformation",
    "license",
    "licenseStatus",
    "channelAssignment"
  ],
  "properties": {
    "palId": {
      "type": "string",
      "description": "PAL-ID of this PAL database record. Format: pal/$MO-$YEAR/$FIPS/$CHANNEL"
    },
    "licensee": {
      "type": "string",
      "description": "Human-readable name of the PAL licensee"
    },
    "userId": {
      "type": "string",
      "description": "User Identifier (UR-ID) of the PAL licensee. This is used by CBSDs requesting PAL spectrum grants from SAS to identify which PAL licensee they are operated by"
    },
    "registrationInformation": {
      "$ref": "#/registrationInfo"
    },
    "license": {
      "$ref": "#/licenseInfo"
    },
    "licenseStatus": {
      "enum": [
        "VALID",
        "RESCINDED",
        "EXPIRED"
      ],
      "description": "License status"
    },
    "channelAssignment": {
      "$ref": "#/channelAssignment"
    }
  },
  "registrationInfo": {
    "type": "object",
    "description": "Information regarding the license described in a PAL database record",
    "properties": {
      "frn": {
        "type": "string",
        "description": "FRN of the license"
      },
      "registrationDate": {
        "type": "string",
        "description": "Date of licensee FCC registration in UTC using the format YYYY-MM-DDThh:mm:ssZ as defined by RFC-3339"
      },
      "licenseConditions": {
        "type": "string",
        "description": "Human-readable string or reference annotating the certification"
      },
      "callSign": {
        "type": "string",
        "description": "call sign of the licensee (as assigned by FCC)"
      }
    }
  },
  "licenseInfo": {
    "type": "object",
    "description": "Information regarding the license described in a PAL database record",
    "properties": {
      "licenseId": {
        "type": "string",
        "description": "FCC-issued license ID"
      },
      "licenseDate": {
        "type": "string",
        "description": "Start date of the license period in UTC using the format YYYY-MM-DDThh:mm:ssZ as defined by RFC-3339"
      },
      "licenseExpiration": {
        "type": "string",
        "description": "Expiration date of the license period in UTC using the format YYYY-MM-DDThh:mm:ssZ as defined by RFC-3339"
      },
      "licenseAreaIdentifier": {
        "type": "string",
        "description": "Human-readable string or reference denoting the license area (e.g. FIPS census tract code)"
      },
      "licenseAreaExtent": {
        "type": "string",
        "description": "Reference to a record in a geographical database represented as a SAS-SAS Zone record providing the extents of the license area. (e.g. “zone/census_tract/census/$YEAR/$FIPS”)"
      },
      "licenseFrequencyChannelId": {
        "type": "string",
        "description": "FCC-supplied identifier for the frequency channel for the PAL"
      }
    }
  },
  "channelAssignment": {
    "type": "object",
    "description": "",
    "required": [
      "primaryAssignment"
    ],
    "properties": {
      "primaryAssignment": {
        "$ref": "file:FrequencyRange.schema.json"
      },
      "secondaryAssignment": {
        "$ref": "file:FrequencyRange.schema.json"
      }
    }
  }
}

=== Wireless-Innovation-Forum/Spectrum-Access-System/src/harness/testcases/testdata/pal_record_0.json
{
  "palId": "pal/05-2017/20041084200/A",
  "licensee": "CBSD Operator No.1",
  "userId": "cbsdOp1",
  "registrationInformation": {
    "frn": "test_fcc_frn_pal_a",
    "registrationDate": "2017-05-01T00:00:00Z"
  },
  "license": {
    "licenseId": "test_fcc_id_pal_a",
    "licenseDate": "2017-05-01T00:00:00Z",
    "licenseExpiration": "2020-07-01T00:00:00Z",
    "licenseAreaIdentifier": "Census Tract 20041084200 County Dickinson State Kansas",
    "licenseAreaExtent": "zone/census_tract/census/2013/20041084200",
    "licenseFrequencyChannelId": "1"
  },
  "licenseStatus": "VALID",
  "channelAssignment": {
    "primaryAssignment": {
      "lowFrequency": 3550000000.0,
      "highFrequency": 3560000000.0
    },
    "secondaryAssignment": {
      "lowFrequency": 3580000000.0,
      "highFrequency": 3590000000.0
    }
  }
}

=== Wireless-Innovation-Forum/Spectrum-Access-System/src/harness/testcases/testdata/pal_db/pal_db_record.json
[
  {
    "license": {
      "licenseAreaExtent": "zone/census_tract/census/2010/20063955100", 
      "licenseFrequencyChannelId": "1", 
      "licenseId": "test_fcc_id_pal_0", 
      "licenseDate": "2017-05-07T00:27:09Z", 
      "licenseAreaIdentifier": "20063955100", 
      "licenseExpiration": "2019-05-07T00:27:09Z"
    }, 
    "registrationInformation": {
      "callSign": "call_sign_pal_0", 
      "frn": "test_fcc_frn_pal_0", 
      "licenseConditions": "license_pal_0", 
      "registrationDate": "2017-05-07T00:27:09Z"
    }, 
    "userId": "test_user_id_a", 
    "licensee": "CBSD Operator No.1", 
    "channelAssignment": {
      "primaryAssignment": {
        "lowFrequency": 3570000000, 
        "highFrequency": 3580000000
      }
    }, 
    "licenseStatus": "VALID", 
    "palId": "pal/05-2017/20063955100/1"
  }, 
  {
    "license": {
      "licenseAreaExtent": "zone/census_tract/census/2010/20063955200", 
      "licenseFrequencyChannelId": "1", 
      "licenseId": "test_fcc_id_pal_1", 
      "licenseDate": "2017-05-07T00:27:09Z", 
      "licenseAreaIdentifier": "20063955200", 
      "licenseExpiration": "2019-05-07T00:27:09Z"
    }, 
    "registrationInformation": {
      "callSign": "call_sign_pal_1", 
      "frn": "test_fcc_frn_pal_1", 
      "licenseConditions": "license_pal_1", 
      "registrationDate": "2017-05-07T00:27:09Z"
    }, 
    "userId": "test_user_id_a", 
    "licensee": "CBSD Operator No.1", 
    "channelAssignment": {
      "primaryAssignment": {
        "lowFrequency": 3570000000, 
        "highFrequency": 3580000000
      }
    }, 
    "licenseStatus": "VALID", 
    "palId": "pal/05-2017/20063955200/1"
  }
]

=== Wireless-Innovation-Forum/Spectrum-Access-System/src/harness/testcases/testdata/pal_database_record_0.json
{
  "palId" : "pal/10-2017/123456789/A",
	"licensee" : "SAS_Administrator_Test",
	"userId" : "test_user_id_c",
	"registrationInformation" : {
	  "frn" : "123456-789",
	  "registrationDate": "2017-06-01"
  },
  "license": {
    "licenseId": "fccId123456789-1",
    "licenseDate": "2017-07-01T00:00:00Z",
    "licenseExpiration": "2020-07-01T00:00:00Z",
    "licenseAreaIdentifier": "Census Tract 123456789, Long Name",
    "licenseAreaExtent": "zone/census_tract/census/2010/123456789",    
    "licenseFrequencyChannelId": "1"
  },
  "licenseStatus": "VALID",
  "channelAssignment": {
    "primaryAssignment": {
      "lowFrequency": 3620000000,
      "highFrequency": 3630000000
    },    
    "secondaryAssignment": {
      "lowFrequency": 3580000000,
      "highFrequency": 3590000000    
    }  
  } 
}
