=== Wireless-Innovation-Forum/Spectrum-Access-System/schema/RegistrationRequest.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Registration parameters provided for a CBSD",
  "type": "object",
  "required": [ "userId", "fccId", "cbsdSerialNumber" ],
  "properties": {
    "userId": { "type": "string",
                "description": "Unique user designator for the operator. Generation mechanism TBD" },
    "fccId": { "type": "string",
               "description": "The certification FCC ID for the hardware" },
    "cbsdSerialNumber": { "type": "string",
                          "description": "Unique identifier for the CBSD chosen by the manufacturer" },
    "cbsdCategory": { "enum" : [ "A", "B" ],
                      "description": "A if the device is Category A; B if it is Category B" },
    "callSign": { "type": "string",
                  "description": "The call sign for the operator. Meaning and origin TBD" },
    "measCapability": { "type": "array",
                        "description": "List of supported sensing capabilities of the device",
                        "items": { "enum": [ "RECEIVED_POWER_WITHOUT_GRANT", "RECEIVED_POWER_WITH_GRANT" ],
                                   "description": "Measurement capabilities of the CBSD." }
                      },
    "groupingParam": {
      "type": "array",
      "description": "List of group memberships of this CBSD.",
      "items": { "$ref": "#/groupParamObject" }
    },
    "cbsdInfo": { "$ref": "#/cbsdInfoObject" },
    "airInterface": { "$ref": "#/airInterfaceObject" },
    "installationParam": { "$ref": "file:InstallationParam.schema.json" }
  },

  "cbsdInfoObject": {
    "type": "object",
    "description": "Container for optional information related to the CBSD hardware and software configuration.",
    "properties": {
      "vendor": { "type": "string",
                  "description": "Name of the CBSD manufacturer" },
      "model": { "type": "string",
                 "description": "Name of the CBSD model." },
      "softwareVersion": { "type": "string",
                           "description": "Name of the CBSD software version." },
      "hardwareVersion": { "type": "string",
                           "description": "Name of the CBSD hardware version." },
      "firmwareVersion": { "type": "string",
                           "description": "Name of the CBSD firmware version." },
      "additionalProperties": true
    }
  },

  "groupParamObject": {
    "type": "object",
    "required": [ "groupType", "groupId" ],
    "description": "Container for information about a CBSD membership group.",
    "properties": {
      "groupType": { "enum": [ "interference-coordination" ],
	             "description": "Type of the group" },
      "groupId": { "type": "string",
	           "description": "ID of the group" }
    }
  },

  "airInterfaceObject": {
    "type": "object",
    "description": "Air interface parameter for a CBSD",
    "required": [ "radioTechnology" ],
    "properties": {
      "radioTechnology": { "enum": [ "E_UTRA" ],
                           "description": "Which PHY radio technology is used by the device in the 3.5GHz band" },
      "supportedSpec": { "type": "string",
                         "description": "Description of the spec of the radio technology supported." }
    }
  }
}

=== Wireless-Innovation-Forum/Spectrum-Access-System/src/harness/testcases/testdata/device_b.json
{
  "fccId": "test_fcc_id_b",
  "userId": "test_user_id_b",
  "cbsdSerialNumber": "test_serial_number_b",
  "callSign": "callsign_b",
  "cbsdCategory": "B",
  "airInterface": {
    "radioTechnology": "E_UTRA"
  },
  "installationParam": {
    "latitude": 37.325056,
    "longitude": -122.084112,
    "height": 9.3,
    "heightType": "AGL",
    "indoorDeployment": true,
    "antennaGain": 16,
    "antennaBeamwidth": 30,
    "antennaAzimuth": 270,
    "antennaDowntilt": -90
  }
}

=== Wireless-Innovation-Forum/Spectrum-Access-System/src/harness/testcases/testdata/device_d.json
{
  "fccId": "test_fcc_id_b2",
  "userId": "test_user_id_b2",
  "cbsdSerialNumber": "test_serial_number_b2",
  "callSign": "callsign_b12345",
  "cbsdCategory": "B",
  "airInterface": {
    "radioTechnology": "E_UTRA"
  },
  "installationParam": {
    "latitude": 36.764571,
    "longitude": -85.075715,
    "height": 8.9,
    "heightType": "AGL",
    "indoorDeployment": false,
    "antennaGain": -30,
    "antennaBeamwidth": 68,
    "antennaAzimuth": 90,
    "antennaDowntilt": -45
  }
}
