=== Wireless-Innovation-Forum/Spectrum-Access-System/schema/zoneData.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "Describe all the PPA Information included in the ZoneData object",
  "type": "object",
  "required": [
    "id",
    "name",
    "creator",
    "usage",
	"terminated",
	"zone"
	
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "id of zone Format: zone/$CREATOR/$ZONE_ID",
	  "pattern" : "zone/.+/.+"
	},
	"name": {
      "type": "string",
      "description": "Human-readable local significant string. The name of this zone."
	},
    "creator": {
      "type": "string",
      "description": "Duman-readable local significant string. The name creator one of (SAS Administrator record ID , Static government zone definition source ID)."
    },
    "usage": {
      "type": "string",
       "enum": [ "CENSUS_TRACT", "PPA", "EXCLUSION_ZONE"],
      "description": "Enumeration describing the usage of the zone."
    },
	"terminated": {
      "type": "boolean",
      "description": "Indicates whether the zone is currently terminated or not"
    },
	"ppaInfo": {
	"$ref": "file:PpaInformation.schema.json"
    },
	"zone": {
	"$ref": "file:Zone.schema.json"
    }
  },
  
   "oneOf": [
      {
         "properties": {
             "usage": {"enum": ["PPA"] }
         },
         "required": ["ppaInfo"]
      },
	  {
         "properties": {
             "usage": {"enum": ["CENSUS_TRACT", "EXCLUSION_ZONE"] }
         }
      }
	  ]
}

=== Wireless-Innovation-Forum/Spectrum-Access-System/src/harness/reference_models/iap/test_data/ppa_0.json
{
  "id": "PPA_P_01",
  "name": "PPA Zone 0",
  "creator": "admin_0",
  "usage": "PPA",
  "terminated": false,
  "ppaInfo": {
        "ppaRegionType": "RURAL",
        "cbsdReferenceId": [
          "cbsd_5",
          "cbsd_3"
        ],
        "palId": [
          "pal_0"
        ],
        "ppaBeginDate": "2016-01-02 08:26:55",
        "ppaExpirationDate": "2020-01-02 08:26:55" 
      },
  "zone": {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "properties": {},
        "geometry": {
          "type": "polygon",
          "coordinates": [
              [
              [
                        -108.05,
                        42.20
                     ],
                     [
                        -107.95,
                        42.20
                     ],
                     [
                        -107.95,
                        42.05
                     ],
                     [
                        -108.05,
                        42.05
                     ],
                     [
                        -108.05,
                        42.20
                     ]
                ]
          ]
        }
      }
    ]
  }
}

=== Wireless-Innovation-Forum/Spectrum-Access-System/src/harness/testcases/testdata/ppa_record_0.json
{
  "id": "zone/ppa/0/0",
  "name": "PPA Zone 0",
  "creator": "0",
  "usage": "PPA",
  "terminated": false,
  "ppaInfo": {
    "palId": [
      "pal/05-2017/20041084200/A"
    ],
    "ppaBeginDate": "2017-05-01T00:00:00Z",
    "ppaExpirationDate": "2020-07-01T00:00:00Z"
  },
  "zone": {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "properties": {},
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                -97.23861694335938,
                38.865374851611634
              ],
              [
                -97.31964111328125,
                38.7615795117574
              ],
              [
                -97.16995239257811,
                38.739088441876866
              ],
              [
                -97.16171264648436,
                38.86751337001198
              ],
              [
                -97.23861694335938,
                38.865374851611634
              ]
            ]
          ]
        }
      }
    ]
  }
}

=== Wireless-Innovation-Forum/Spectrum-Access-System/src/harness/reference_models/iap/test_data/ppa_3.json
{
  "id": "PPA_P_0333",
  "name": "PPA Zone 2",
  "creator": "admin_2",
  "usage": "PPA",
  "terminated": false,
  "ppaInfo": {
        "ppaRegionType": "RURAL",
        "cbsdReferenceId": [
          "cbsd_3"
        ],
        "palId": [
          "pal_3"        ],
        "ppaBeginDate": "2016-01-02 08:26:55",
        "ppaExpirationDate": "2020-01-02 08:26:55" 
      },
  "zone": {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "properties": {},
        "geometry": {
          "type": "Polygon",
          "coordinates": [
              [
              [
                        -120.20,
                        34.75
                     ],
                     [
                        -120.15,
                        34.75
                     ],
                     [
                        -120.15,
                        34.70
                     ],
                     [
                        -120.20,
                        34.70
                     ],
                     [
                        -120.20,
                        34.75
                     ]
                ]
          ]
        }
      }
    ]
  }
}

=== Wireless-Innovation-Forum/Spectrum-Access-System/schema/ZoneDataOfPpaExample.json
{"id":"zone/ppa/SAS_Admin_1/1","name":"PPA Zone 0","creator":"SAS_Admin_1","usage":"PPA","terminated":false,"ppaInfo":{"palId":["pal/05-2017/20041084200/A"],"ppaBeginDate":"2017-05-01T00:00:00Z","ppaExpirationDate":"2017-05-01T00:00:00Z","cbsdReferenceId":["CBSD_228_RED/c36153d7b423721145f3f3ac9e28bd02211ff03a"]},"zone":{"features":[{"geometry":{"coordinates":[[[-97.2386169433594,38.8653748516116],[-97.3196411132812,38.7615795117574],[-97.1699523925781,38.7390884418769],[-97.1617126464844,38.867513370012],[-97.2386169433594,38.8653748516116]]],"type":"Polygon"},"properties":{},"type":"Feature"}],"type":"FeatureCollection"}}

=== Wireless-Innovation-Forum/Spectrum-Access-System/src/harness/reference_models/pre_iap_filtering/testdata/testset1/ppa_0.json
{
  "id": "PPA_0",
  "name": "PPA Zone 0",
  "creator": "admin_0",
  "usage": "PPA",
  "terminated": false,
  "ppaInfo": {
        "ppaRegionType": "RURAL",
        "cbsdReferenceId": [
          "cbsd_5",
          "cbsd_3"
        ],
        "palId": [
          "pal_0",
          "pal_1",
          "pal_2"
        ],
        "ppaBeginDate": "2016-01-02 08:26:55",
        "ppaExpirationDate": "2020-01-02 08:26:55" 
      },
  "zone": {
    "type": "FeatureCollection",
    "features": [
      {
        "type": "Feature",
        "properties": {},
        "geometry": {
          "type": "Polygon",
          "coordinates": [
              [
                     [
                       -101.48221, 40.50541
                     ],
                     [
                       -101.50371, 40.50972
                     ],
                     [
                       -101.51766, 40.48919
                     ],
                     [
                       -101.49036, 40.48978
                     ]
                ]
          ]
        }
      }
    ]
  }
}
